// <auto-generated />
using System;
using Birdsoft.Security.Data.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Security.Data.EfCore.Migrations
{
    [DbContext(typeof(SecurityDbContext))]
    [Migration("20260114161143_AddProductsAndTenantProducts")]
    partial class AddProductsAndTenantProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.AccessTokenDenylistEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "Jti");

                    b.HasIndex("TenantId", "ExpiresAt");

                    b.ToTable("access_token_denylist", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.AuthEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OurSubject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.HasIndex("TenantId", "OurSubject");

                    b.HasIndex("TenantId", "SessionId");

                    b.HasIndex("TenantId", "Type");

                    b.HasIndex("TenantId", "Code", "OccurredAt");

                    b.HasIndex("TenantId", "OurSubject", "OccurredAt");

                    b.ToTable("security_audit_logs", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.AuthStateEntity", b =>
                {
                    b.Property<string>("State")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeVerifier")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nonce")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("State");

                    b.HasIndex("TenantId", "ExpiresAt");

                    b.HasIndex("TenantId", "UsedAt");

                    b.ToTable("auth_states", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.AuthzTenantVersionEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ModelVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId");

                    b.HasIndex("TenantId", "UpdatedAt");

                    b.ToTable("authz_tenant_versions", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.ExternalIdentityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OurSubject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSub")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Enabled");

                    b.HasIndex("TenantId", "OurSubject");

                    b.HasIndex("TenantId", "Provider");

                    b.HasIndex("TenantId", "Provider", "Issuer", "ProviderSub")
                        .IsUnique();

                    b.ToTable("external_identities", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.LocalAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HashVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastPasswordChangeAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OurSubject")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameOrEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LockedUntil");

                    b.HasIndex("TenantId", "OurSubject")
                        .IsUnique();

                    b.HasIndex("TenantId", "UsernameOrEmail")
                        .IsUnique();

                    b.ToTable("subject_credentials", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.OidcProviderConfigEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Authority")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CallbackPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopesJson")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "Provider");

                    b.HasIndex("TenantId", "Enabled");

                    b.ToTable("oidc_providers", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.PermissionEntity", b =>
                {
                    b.Property<Guid>("PermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PermKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PermId");

                    b.HasIndex("PermKey")
                        .IsUnique();

                    b.HasIndex("ProductKey");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductKey")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssuedSubjectTokenVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssuedTenantTokenVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OurSubject")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReplacedByRefreshTokenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenLookup")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExpiresAt");

                    b.HasIndex("TenantId", "OurSubject");

                    b.HasIndex("TenantId", "RevokedAt");

                    b.HasIndex("TenantId", "SessionId")
                        .IsUnique();

                    b.HasIndex("TenantId", "TokenHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "TokenLookup");

                    b.HasIndex("TenantId", "OurSubject", "RevokedAt", "ExpiresAt");

                    b.ToTable("refresh_sessions", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "RoleId");

                    b.HasIndex("TenantId", "RoleName")
                        .IsUnique();

                    b.HasIndex("TenantId", "UpdatedAt");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "RoleId", "PermId");

                    b.HasIndex("PermId");

                    b.HasIndex("TenantId", "PermId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.SubjectEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OurSubject")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "OurSubject");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "UpdatedAt");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.SubjectPermissionEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OurSubject")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "OurSubject", "PermId");

                    b.HasIndex("PermId");

                    b.HasIndex("TenantId", "PermId");

                    b.ToTable("subject_permissions", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.SubjectRoleEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OurSubject")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "OurSubject", "RoleId");

                    b.HasIndex("TenantId", "RoleId");

                    b.ToTable("subject_roles", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.SubjectScopeEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OurSubject")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "OurSubject", "ScopeKey");

                    b.HasIndex("TenantId", "ScopeKey");

                    b.ToTable("subject_scopes", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.TenantEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.TenantProductEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "ProductKey");

                    b.HasIndex("ProductKey", "Status");

                    b.HasIndex("TenantId", "EndAt");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "ProductKey", "Status");

                    b.ToTable("tenant_products", (string)null);
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.RolePermissionEntity", b =>
                {
                    b.HasOne("Birdsoft.Security.Data.EfCore.Entities.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Birdsoft.Security.Data.EfCore.Entities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.SubjectPermissionEntity", b =>
                {
                    b.HasOne("Birdsoft.Security.Data.EfCore.Entities.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Birdsoft.Security.Data.EfCore.Entities.SubjectEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OurSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.SubjectRoleEntity", b =>
                {
                    b.HasOne("Birdsoft.Security.Data.EfCore.Entities.SubjectEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OurSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Birdsoft.Security.Data.EfCore.Entities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Birdsoft.Security.Data.EfCore.Entities.SubjectScopeEntity", b =>
                {
                    b.HasOne("Birdsoft.Security.Data.EfCore.Entities.SubjectEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OurSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
